import os

API_ID = int(os.getenv("API_ID"))
API_HASH = os.getenv("API_HASH")

REDDIT_CLIENT_ID = os.getenv("REDDIT_CLIENT_ID")
REDDIT_SECRET = os.getenv("REDDIT_SECRET")
REDDIT_USER_AGENT = os.getenv("REDDIT_USER_AGENT")

TON_PAYMENT_LINK = os.getenv("TON_PAYMENT_LINK")
USDT_PAYMENT_LINK = os.getenv("USDT_PAYMENT_LINK")
